### ISSUE TITLE
GoogleIdTokenVerifier: error trying to create an instance of it

### ISSUE THREAD

**Issue by giacomo-m** [googleapis/google-api-java-client#2241] opened 2023-01-23 15:21 UTC
i'm trying to integrate the google login function on my website and i'm following the relative google doc for the server side token validation: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token?hl=en .

I've created a simple test app with the GoogleIdTokenVerifier declaration but i'm getting the error:
`java.lang.NoClassDefFoundError: com/google/api/client/json/JsonFactory`

This is the test app with the GoogleIdTokenVerifier declaration:

```
package test;

import java.util.Collections;

import com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.gson.GsonFactory;

public class Main {

    public static void main(String[] args) {
        
        try {
            
            HttpTransport transport = new NetHttpTransport();
            
            GoogleIdTokenVerifier verifier = new GoogleIdTokenVerifier.Builder(transport, new GsonFactory())
                // Specify the CLIENT_ID of the app that accesses the backend:
                .setAudience(Collections.singletonList("xxx.apps.googleusercontent.com"))
                // Or, if multiple clients access the backend:
                //.setAudience(Arrays.asList(CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3))
                .build();

            
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

}
```

and this is the pom.xml i used for the dependencies:
```
<project>

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1</version>

<dependencies>
   <dependency>
     <groupId>com.google.api-client</groupId>
     <artifactId>google-api-client</artifactId>
     <version>2.1.3</version>
   </dependency>
   
  </dependencies>

  
</project>

```
What am i doing wrong?

Thanks.
Giacomo

**Comment by diegomarquezp** [comment] 2023-01-25 22:58
Hi @giacomo-m I could not reproduce the error by setting up an empty maven application using the main class and dependency you provided. I would try cleaning local repositories.
Also, please consider reaching out to our support hub if you have a support plan for a faster response

**Comment by alicejli** [comment] 2023-07-12 14:56
Closing due to lack of follow-up. Please re-open or create a new issue if this is still needed.

**Closed by alicejli** 2023-07-12 14:56 UTC
Labels: type: question, priority: p3
