### ISSUE TITLE
Blogger API v3 : when calling /posts/search/, parameter nextPageToken is ignored

### ISSUE THREAD

**Issue by ludovic-lambert** [googleapis/google-api-java-client#1381] opened 2019-09-19 16:29 UTC
Env : javascript, using XMLHttpRequest and JSON API.

When calling `{URL}/posts/?{parameters}` :
- the 10 first items are returned
- if the response contains more than 10 items, an attribute `{ "nextPageToken":"xyz" }` is added to the JSON data response.

Then when calling `{URL}/posts/?{parameters}&pageToken={nextPageToken}` :
- the response contains the next 10 items
- a new `nextPageToken` is returned until no more page

=> Looks like the expected behavior, working fine.

**However:**
When calling `{URL}/posts/search/?q={query_string}{parameters}` :
- the 10 first items are returned
- if the response contains more than 10 items, an attribute `{ "nextPageToken":"xyz" }` is added to the JSON data response.

Then when calling 
`{URL}/posts/search/?q={query_string}{parameters}&pageToken={nextPageToken}` :
**- the 10 first items are displayed again (ie not the next 10),**
**- returned `nextPageToken` is the same than first call**

Looks like pageToken is ignored for /posts/search/.
Is this the expected behavior ? How to access items of /posts/search/ response returning more than 10 items?

**Comment by chingor13** [comment] 2019-09-25 14:51
This is the repository for the java client so this issue doesn't belong here.

However, to answer the question, the [posts search endpoint](https://github.com/googleapis/discovery-artifact-manager/blob/5fafbc3f1330a4536c3d0f674a9ddce55c01aef3/discoveries/blogger.v3.json#L2365-L2415) does not appear to accept a `pageToken` parameter.

**Comment by ludovic-lambert** [comment] 2019-09-25 22:05
Hi, thank you for your answer. According to the fact a nextPageToken is provided, and as it should be possible to retrive more than 10 items from a /posts/search/, I think this might be a bug. Could you please guide me to the right place to open this issue?

**Comment by pradyum619** [comment] 2020-10-24 07:41
Is the issue resolved? if yes please share the solution, I am facing the same issue, can't get the next 10 items in the search endpoint.

**Comment by lglf77** [comment] 2021-11-20 00:26
Meu blogger na api não tem nextPageToken nem nextPage. O que fazer? Só tenho 3 postagens por página.  E 3 páginas ao total do blogger. 9 postagens. O blogger retirou isso para novos blogs?

**Comment by mortezaadi** [comment] 2022-01-12 18:27
Definitely, it's not a bug, though it needs more clarification, you can refer to this document from Blogger API v3 (here][1].

to get the pagination work you need to call the API with maxResults={pageSize} then you will get an extra value in the response 'nextPageToken', you should use the value of this field and pass it with. 'pageToken' **NOT** 'nextPageToken'

    https://blablabla?maxResults=10&pageToken={VALUE_OF_NEXTPAGETOKEN}

when you reach the end of the list you won't get the nextPageToken anymore and it means nothing more to fetch.

  [1]: https://developers.google.com/blogger/docs/3.0/reference/posts/list

**Comment by meltsufin** [comment] 2022-12-04 03:33
It doesn't appear to be an issue with the library itself. If anything, it's the service.

**Comment by burkedavison** [comment] 2024-09-26 19:05
Closing this issue as we are unable to provide adequate customer support through this forum. If you feel there is a bug or a feature request associated with this ticket, please open a new issue. Otherwise, https://cloud.google.com/support is best able to provide timely answers to API-specific questions.

**Closed by burkedavison** 2024-09-26 19:05 UTC
Labels: type: question, priority: p4

**Comment by Madirex** [comment] 2024-09-26 19:48
The error persists and is still occurring. Google support hasn't been able to resolve the issue.
