### ISSUE TITLE
Unable to execute GmailQuickStart in Katalon Studio

### ISSUE THREAD

**Issue by plaidshirtakos** [googleapis/google-api-java-client#1755] opened 2021-03-29 09:59 UTC
I try to use this article: https://developers.google.com/gmail/api/quickstart/java. Following jars are imported:
```
commons-codec-1.15.jar
commons-logging-1.2.jar
google-api-client-1.31.3.jar
google-api-client-extensions-1.6.0-beta.jar
google-api-client-jackson2-1.31.3.jar
google-api-client-java6-1.31.3.jar
google-api-services-gmail-v1-rev110-1.25.0.jar
google-http-client-1.39.1.jar
google-http-client-jackson2-1.39.1.jar
google-oauth-client-java6-1.31.4.jar
google-oauth-client-jetty-1.31.4.jar
guava-30.1.1-jre.jar
httpclient-4.5.13.jar
httpcore-4.4.14.jar
j2objc-annotations-1.3.jar
jackson-core-2.12.2.jar
jsr305-3.0.2.jar
```
Exception is occured during execution, after authentication:
```
Caused by: java.lang.NoSuchMethodError: com.google.api.client.http.HttpRequest.setResponseReturnRawInputStream(Z)Lcom/google/api/client/http/HttpRequest;
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:418)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)
	at check.mail.GmailQuickStart.main(GmailQuickStart.groovy:92)
	... 14 more
```

**Comment by Neenu1995** [comment] 2021-03-29 17:51
This issue is duplicate of #1753

How are you importing these particular versions of the dependencies in the project? The information currently provided is not enough to debug the issue properly.

That said, this looks like a dependency issue. Checking the dependency tree can give a clearer understanding of the error. Refer [this](https://github.com/googleapis/google-cloud-java/blob/master/TROUBLESHOOTING.md) troubleshooting document for detailed instructions. 
The suggested method to resolve dependency issues is to use [`libraries-bom`](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM).

**Comment by plaidshirtakos** [comment] 2021-03-30 09:25
Thanks, I found the problem in the meantime. Katalon Studio uses also this package, but version 1.22.0. So method is resolved from that package, but it was introduced in later version. So problem is caused by KS in that case.

**Closed** 2021-05-05 12:12 UTC
Labels: type: question
